# Generated by Django 4.2.25 on 2025-10-23 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del héroe (máximo 255 caracteres)', max_length=255, verbose_name='Nombre del héroe')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del héroe', null=True, verbose_name='Descripción')),
                ('poder_principal', models.CharField(blank=True, help_text='El superpoder principal del héroe', max_length=255, null=True, verbose_name='Poder principal')),
                ('nivel', models.IntegerField(default=1, help_text='Nivel de poder del héroe (1-100)', verbose_name='Nivel de poder')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el héroe', verbose_name='Fecha de creación')),
                ('team', models.ForeignKey(help_text='El equipo al que pertenece este héroe', on_delete=django.db.models.deletion.CASCADE, related_name='heroes', to='teams.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Héroe',
                'verbose_name_plural': 'Héroes',
                'db_table': 'heroes',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['team'], name='idx_hero_team')],
            },
        ),
    ]
